### ISSUE TITLE
Can not push project to balenaCloud

### ISSUE THREAD

**Issue by idoodler** [balena-io-playground/balena-cam#42]
I recently pulled this project and tried to deploy it on a `Raspberry Pi Zero W` running `balenaOS 2.32.0+rev1`.

However I am unable to push this project using `balena push <PROJECT_NAME>`

<details><summary>Log from balena push</summary>
<p>

```shell
[Info]        Starting build for ImgFetcher, user gh_idoodler
[Info]        Dashboard link: https://dashboard.balena-cloud.com/apps/1498507/devices
[Info]        Building on arm01
[Info]        Pulling previous images for caching purposes...
[Success]     Successfully pulled cache images
[balena-cam]  Step 1/10 : FROM balenalib/raspberry-pi-debian:stretch
[balena-cam]   ---> b5c859a71dc3
[balena-cam]  Step 2/10 : RUN echo "deb http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list
[balena-cam]  Using cache
[balena-cam]   ---> db9231a20254
[balena-cam]  Step 3/10 : RUN apt-get update &&   apt-get install -yq     gstreamer-1.0     v4l-utils     libopus-dev     libvpx-dev     python3     python3-dev     python3-pip     python3-setuptools     libsrtp2-dev     libopencv-dev     libatlas3-base     libjasper-dev     libilmbase12     libopenexr22     libavformat-dev     libswscale-dev     libqtgui4     libqt4-test     libavdevice-dev     libavfilter-dev     libavcodec-dev   && apt-get clean && rm -rf /var/lib/apt/lists/*
[balena-cam]   ---> Running in f2757c715856
[balena-cam]  Ign:1 http://deb.debian.org/debian jessie InRelease
[balena-cam]  Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]
[balena-cam]  Get:3 http://deb.debian.org/debian jessie Release [77.3 kB]
[balena-cam]  Get:4 http://archive.raspbian.org/raspbian stretch InRelease [15.0 kB]
[balena-cam]  Get:5 http://deb.debian.org/debian jessie Release.gpg [1652 B]
[balena-cam]  Get:6 http://archive.raspberrypi.org/debian stretch/ui armhf Packages [45.0 kB]
[balena-cam]  Get:7 http://archive.raspbian.org/raspbian stretch/firmware armhf Packages [1201 B]
[balena-cam]  Get:8 http://archive.raspberrypi.org/debian stretch/main armhf Packages [221 kB]
[balena-cam]  Ign:5 http://deb.debian.org/debian jessie Release.gpg
[balena-cam]  Get:9 http://archive.raspbian.org/raspbian stretch/contrib armhf Packages [66.2 kB]
[balena-cam]  Get:10 http://deb.debian.org/debian jessie/main armhf Packages [8898 kB]
[balena-cam]  Get:11 http://archive.raspbian.org/raspbian stretch/rpi armhf Packages [1299 B]
[balena-cam]  Get:12 http://archive.raspbian.org/raspbian stretch/non-free armhf Packages [116 kB]
[balena-cam]  Get:13 http://archive.raspbian.org/raspbian stretch/main armhf Packages [16.4 MB]
[balena-cam]  Fetched 25.9 MB in 3s (6565 kB/s)
[balena-cam]  Reading package lists...
[balena-cam]  W: GPG error: http://deb.debian.org/debian jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7638D0442B90D010 NO_PUBKEY CBF8D6FD518E17E1
[balena-cam]  W: The repository 'http://deb.debian.org/debian jessie Release' is not signed.
[balena-cam]  
[balena-cam]  Reading package lists...
[balena-cam]  Building dependency tree...
[balena-cam]  Reading state information...
[balena-cam]  The following additional packages will be installed:
[balena-cam]    dh-python fontconfig fontconfig-config fonts-dejavu-core gir1.2-atk-1.0
[balena-cam]    gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gtk-2.0
[balena-cam]    gir1.2-pango-1.0 gnome-icon-theme gtk-update-icon-cache hicolor-icon-theme
[balena-cam]    icu-devtools iso-codes libasan3 libasound2 libasound2-data libass5
[balena-cam]    libasyncns0 libatk1.0-0 libatk1.0-data libatk1.0-dev libatomic1 libaudio2
[balena-cam]    libavahi-client3 libavahi-common-data libavahi-common3 libavc1394-0
[balena-cam]    libavcodec57 libavdevice57 libavfilter6 libavformat57 libavresample-dev
[balena-cam]    libavresample3 libavutil-dev libavutil55 libblas-common libbluray2 libbs2b0
[balena-cam]    libbsd0 libc-dev-bin libc6-dev libcaca0 libcairo-gobject2
[balena-cam]    libcairo-script-interpreter2 libcairo2 libcairo2-dev libcap2-bin
[balena-cam]    libcdio-cdda1 libcdio-paranoia1 libcdio13 libchromaprint1 libcroco3 libcups2
[balena-cam]    libcv-dev libcvaux-dev libdatrie1 libdc1394-22 libdc1394-22-dev
[balena-cam]    libdouble-conversion1 libdpkg-perl libebur128-1 libegl1-mesa libexpat1
[balena-cam]    libexpat1-dev libfftw3-double3 libflac8 libflite1 libfontconfig1
[balena-cam]    libfontconfig1-dev libfreetype6 libfreetype6-dev libfribidi0 libgbm1
[balena-cam]    libgcc-6-dev libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev
[balena-cam]    libgfortran3 libgirepository-1.0-1 libgl1-mesa-glx libglapi-mesa
[balena-cam]    libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libgme0 libgomp1
[balena-cam]    libgraphite2-3 libgraphite2-dev libgsm1 libgstreamer-plugins-base1.0-0
[balena-cam]    libgstreamer1.0-0 libgtk2.0-0 libgtk2.0-common libgtk2.0-dev libharfbuzz-dev
[balena-cam]    libharfbuzz-gobject0 libharfbuzz-icu0 libharfbuzz0b libhighgui-dev
[balena-cam]    libice-dev libice6 libicu-dev libicu57 libiec61883-0 libilmbase-dev
[balena-cam]    libjack-jackd2-0 libjasper1 libjbig-dev libjbig0 libjpeg-dev libjpeg62-turbo
[balena-cam]    libjpeg62-turbo-dev liblcms2-2 liblzma-dev liblzo2-2 libmng1 libmp3lame0
[balena-cam]    libmpdec2 libmpg123-0 libogg0 libopenal-data libopenal1
[balena-cam]    libopencv-calib3d-dev libopencv-calib3d2.4v5 libopencv-contrib-dev
[balena-cam]    libopencv-contrib2.4v5 libopencv-core-dev libopencv-core2.4v5
[balena-cam]    libopencv-features2d-dev libopencv-features2d2.4v5 libopencv-flann-dev
[balena-cam]    libopencv-flann2.4v5 libopencv-gpu-dev libopencv-gpu2.4v5
[balena-cam]    libopencv-highgui-dev libopencv-highgui2.4-deb0 libopencv-imgproc-dev
[balena-cam]    libopencv-imgproc2.4v5 libopencv-legacy-dev libopencv-legacy2.4v5
[balena-cam]    libopencv-ml-dev libopencv-ml2.4v5 libopencv-objdetect-dev
[balena-cam]    libopencv-objdetect2.4v5 libopencv-ocl-dev libopencv-ocl2.4v5
[balena-cam]    libopencv-photo-dev libopencv-photo2.4v5 libopencv-stitching-dev
[balena-cam]    libopencv-stitching2.4v5 libopencv-superres-dev libopencv-superres2.4v5
[balena-cam]    libopencv-ts-dev libopencv-ts2.4v5 libopencv-video-dev libopencv-video2.4v5
[balena-cam]    libopencv-videostab-dev libopencv-videostab2.4v5 libopencv2.4-java
[balena-cam]    libopencv2.4-jni libopenexr-dev libopenjp2-7 libopenmpt0 libopus0
[balena-cam]    liborc-0.4-0 libpango-1.0-0 libpango1.0-dev libpangocairo-1.0-0
[balena-cam]    libpangoft2-1.0-0 libpangoxft-1.0-0 libpcap0.8 libpcap0.8-dev libpcre16-3
[balena-cam]    libpcre3-dev libpcre32-3 libpcrecpp0v5 libpgm-5.2-0 libpixman-1-0
[balena-cam]    libpixman-1-dev libpng-dev libpostproc-dev libpostproc54
[balena-cam]    libpthread-stubs0-dev libpulse0 libpython3-dev libpython3-stdlib
[balena-cam]    libpython3.5 libpython3.5-dev libpython3.5-minimal libpython3.5-stdlib
[balena-cam]    libqt5core5a libqt5glib-2.0-0 libqtcore4 libqtglib-2.0-0 libraw1394-11
[balena-cam]    libraw1394-dev librsvg2-2 librsvg2-common librubberband2 libsamplerate0
[balena-cam]    libsdl2-2.0-0 libshine3 libslang2 libsm-dev libsm6 libsnappy1v5 libsndfile1
[balena-cam]    libsndio6.1 libsodium18 libsoxr0 libspeex1 libsrtp2-1 libssh-gcrypt-4
[balena-cam]    libstdc++-6-dev libswresample-dev libswresample2 libswscale4 libthai-data
[balena-cam]    libthai0 libtheora0 libtiff5 libtiff5-dev libtiffxx5 libtwolame0 libubsan0
[balena-cam]    libv4l-0 libv4l2rds0 libv4lconvert0 libva-drm1 libva-x11-1 libva1 libvdpau1
[balena-cam]    libvorbis0a libvorbisenc2 libvorbisfile3 libvpx4 libwavpack1
[balena-cam]    libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa
[balena-cam]    libwayland-server0 libwebp6 libwebpmux2 libwrap0 libx11-6 libx11-data
[balena-cam]    libx11-dev libx11-xcb1 libx264-148 libx265-95 libxau-dev libxau6
[balena-cam]    libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0
[balena-cam]    libxcb-render0-dev libxcb-shape0 libxcb-shm0 libxcb-shm0-dev libxcb-sync1
[balena-cam]    libxcb-xfixes0 libxcb1 libxcb1-dev libxcomposite-dev libxcomposite1
[balena-cam]    libxcursor-dev libxcursor1 libxdamage-dev libxdamage1 libxdmcp-dev libxdmcp6
[balena-cam]    libxext-dev libxext6 libxfixes-dev libxfixes3 libxft-dev libxft2 libxi-dev
[balena-cam]    libxi6 libxinerama-dev libxinerama1 libxkbcommon0 libxml2 libxml2-utils
[balena-cam]    libxrandr-dev libxrandr2 libxrender-dev libxrender1 libxshmfence1 libxss1
[balena-cam]    libxt6 libxtst6 libxv1 libxvidcore4 libxxf86vm1 libzmq5 libzvbi-common
[balena-cam]    libzvbi0 linux-libc-dev mime-support pkg-config python-pip-whl
[balena-cam]    python3-minimal python3-pkg-resources python3.5 python3.5-dev
[balena-cam]    python3.5-minimal qtcore4-l10n shared-mime-info ucf x11-common
[balena-cam]    x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
[balena-cam]    x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev x11proto-randr-dev
[balena-cam]    x11proto-render-dev x11proto-xext-dev x11proto-xinerama-dev xkb-data
[balena-cam]    xorg-sgml-doctools xtrans-dev zlib1g-dev
[balena-cam]  Suggested packages:
[balena-cam]    isoquery libasound2-plugins alsa-utils nas libbluray-bdj glibc-doc
[balena-cam]    manpages-dev libcairo2-doc cups-common debian-keyring gcc | c-compiler
[balena-cam]    binutils patch libfftw3-bin libfftw3-dev alsa-base libglib2.0-doc
[balena-cam]    libvisual-0.4-plugins gstreamer1.0-tools gvfs libgtk2.0-doc libice-doc
[balena-cam]    icu-doc jackd2 libjasper-runtime liblcms2-utils liblzma-doc libportaudio2
[balena-cam]    opus-tools imagemagick libpango1.0-doc pulseaudio qt4-qtconfig
[balena-cam]    libraw1394-doc librsvg2-bin libsm-doc sndiod speex libsrtp2-docs
[balena-cam]    libstdc++-6-doc libxcb-doc libxext-doc python3-doc python3-tk python3-venv
[balena-cam]    python-setuptools-doc python3.5-venv python3.5-doc binfmt-support
[balena-cam]  Recommended packages:
[balena-cam]    libaacs0 manpages manpages-dev libpam-cap libfile-fcntllock-perl bzip2
[balena-cam]    libgl1-mesa-dri xdg-user-dirs gstreamer1.0-plugins-base libgail-common
[balena-cam]    libgtk2.0-bin python debhelper opencv-data libpng-tools qttranslations5-l10n
[balena-cam]    qt-at-spi libraw1394-tools va-driver-all | va-driver vdpau-driver-all
[balena-cam]    | vdpau-driver tcpd libx11-doc xml-core file build-essential python3-wheel
[balena-cam]  The following NEW packages will be installed:
[balena-cam]    dh-python fontconfig fontconfig-config fonts-dejavu-core gir1.2-atk-1.0
[balena-cam]    gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gstreamer-1.0
[balena-cam]    gir1.2-gtk-2.0 gir1.2-pango-1.0 gnome-icon-theme gtk-update-icon-cache
[balena-cam]    hicolor-icon-theme icu-devtools iso-codes libasan3 libasound2
[balena-cam]    libasound2-data libass5 libasyncns0 libatk1.0-0 libatk1.0-data libatk1.0-dev
[balena-cam]    libatlas3-base libatomic1 libaudio2 libavahi-client3 libavahi-common-data
[balena-cam]    libavahi-common3 libavc1394-0 libavcodec-dev libavcodec57 libavdevice-dev
[balena-cam]    libavdevice57 libavfilter-dev libavfilter6 libavformat-dev libavformat57
[balena-cam]    libavresample-dev libavresample3 libavutil-dev libavutil55 libblas-common
[balena-cam]    libbluray2 libbs2b0 libbsd0 libc-dev-bin libc6-dev libcaca0
[balena-cam]    libcairo-gobject2 libcairo-script-interpreter2 libcairo2 libcairo2-dev
[balena-cam]    libcap2-bin libcdio-cdda1 libcdio-paranoia1 libcdio13 libchromaprint1
[balena-cam]    libcroco3 libcups2 libcv-dev libcvaux-dev libdatrie1 libdc1394-22
[balena-cam]    libdc1394-22-dev libdouble-conversion1 libdpkg-perl libebur128-1
[balena-cam]    libegl1-mesa libexpat1 libexpat1-dev libfftw3-double3 libflac8 libflite1
[balena-cam]    libfontconfig1 libfontconfig1-dev libfreetype6 libfreetype6-dev libfribidi0
[balena-cam]    libgbm1 libgcc-6-dev libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common
[balena-cam]    libgdk-pixbuf2.0-dev libgfortran3 libgirepository-1.0-1 libgl1-mesa-glx
[balena-cam]    libglapi-mesa libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev
[balena-cam]    libgme0 libgomp1 libgraphite2-3 libgraphite2-dev libgsm1
[balena-cam]    libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk2.0-0
[balena-cam]    libgtk2.0-common libgtk2.0-dev libharfbuzz-dev libharfbuzz-gobject0
[balena-cam]    libharfbuzz-icu0 libharfbuzz0b libhighgui-dev libice-dev libice6 libicu-dev
[balena-cam]    libicu57 libiec61883-0 libilmbase-dev libilmbase12 libjack-jackd2-0
[balena-cam]    libjasper-dev libjasper1 libjbig-dev libjbig0 libjpeg-dev libjpeg62-turbo
[balena-cam]    libjpeg62-turbo-dev liblcms2-2 liblzma-dev liblzo2-2 libmng1 libmp3lame0
[balena-cam]    libmpdec2 libmpg123-0 libogg0 libopenal-data libopenal1
[balena-cam]    libopencv-calib3d-dev libopencv-calib3d2.4v5 libopencv-contrib-dev
[balena-cam]    libopencv-contrib2.4v5 libopencv-core-dev libopencv-core2.4v5 libopencv-dev
[balena-cam]    libopencv-features2d-dev libopencv-features2d2.4v5 libopencv-flann-dev
[balena-cam]    libopencv-flann2.4v5 libopencv-gpu-dev libopencv-gpu2.4v5
[balena-cam]    libopencv-highgui-dev libopencv-highgui2.4-deb0 libopencv-imgproc-dev
[balena-cam]    libopencv-imgproc2.4v5 libopencv-legacy-dev libopencv-legacy2.4v5
[balena-cam]    libopencv-ml-dev libopencv-ml2.4v5 libopencv-objdetect-dev
[balena-cam]    libopencv-objdetect2.4v5 libopencv-ocl-dev libopencv-ocl2.4v5
[balena-cam]    libopencv-photo-dev libopencv-photo2.4v5 libopencv-stitching-dev
[balena-cam]    libopencv-stitching2.4v5 libopencv-superres-dev libopencv-superres2.4v5
[balena-cam]    libopencv-ts-dev libopencv-ts2.4v5 libopencv-video-dev libopencv-video2.4v5
[balena-cam]    libopencv-videostab-dev libopencv-videostab2.4v5 libopencv2.4-java
[balena-cam]    libopencv2.4-jni libopenexr-dev libopenexr22 libopenjp2-7 libopenmpt0
[balena-cam]    libopus-dev libopus0 liborc-0.4-0 libpango-1.0-0 libpango1.0-dev
[balena-cam]    libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0 libpcap0.8
[balena-cam]    libpcap0.8-dev libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5
[balena-cam]    libpgm-5.2-0 libpixman-1-0 libpixman-1-dev libpng-dev libpostproc-dev
[balena-cam]    libpostproc54 libpthread-stubs0-dev libpulse0 libpython3-dev
[balena-cam]    libpython3-stdlib libpython3.5 libpython3.5-dev libpython3.5-minimal
[balena-cam]    libpython3.5-stdlib libqt4-test libqt5core5a libqt5glib-2.0-0
[balena-cam]    libqt5gstreamer-1.0-0 libqtcore4 libqtglib-2.0-0 libqtgstreamer-1.0-0
[balena-cam]    libqtgui4 libraw1394-11 libraw1394-dev librsvg2-2 librsvg2-common
[balena-cam]    librubberband2 libsamplerate0 libsdl2-2.0-0 libshine3 libslang2 libsm-dev
[balena-cam]    libsm6 libsnappy1v5 libsndfile1 libsndio6.1 libsodium18 libsoxr0 libspeex1
[balena-cam]    libsrtp2-1 libsrtp2-dev libssh-gcrypt-4 libstdc++-6-dev libswresample-dev
[balena-cam]    libswresample2 libswscale-dev libswscale4 libthai-data libthai0 libtheora0
[balena-cam]    libtiff5 libtiff5-dev libtiffxx5 libtwolame0 libubsan0 libv4l-0 libv4l2rds0
[balena-cam]    libv4lconvert0 libva-drm1 libva-x11-1 libva1 libvdpau1 libvorbis0a
[balena-cam]    libvorbisenc2 libvorbisfile3 libvpx-dev libvpx4 libwavpack1
[balena-cam]    libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa
[balena-cam]    libwayland-server0 libwebp6 libwebpmux2 libwrap0 libx11-6 libx11-data
[balena-cam]    libx11-dev libx11-xcb1 libx264-148 libx265-95 libxau-dev libxau6
[balena-cam]    libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0
[balena-cam]    libxcb-render0-dev libxcb-shape0 libxcb-shm0 libxcb-shm0-dev libxcb-sync1
[balena-cam]    libxcb-xfixes0 libxcb1 libxcb1-dev libxcomposite-dev libxcomposite1
[balena-cam]    libxcursor-dev libxcursor1 libxdamage-dev libxdamage1 libxdmcp-dev libxdmcp6
[balena-cam]    libxext-dev libxext6 libxfixes-dev libxfixes3 libxft-dev libxft2 libxi-dev
[balena-cam]    libxi6 libxinerama-dev libxinerama1 libxkbcommon0 libxml2 libxml2-utils
[balena-cam]    libxrandr-dev libxrandr2 libxrender-dev libxrender1 libxshmfence1 libxss1
[balena-cam]    libxt6 libxtst6 libxv1 libxvidcore4 libxxf86vm1 libzmq5 libzvbi-common
[balena-cam]    libzvbi0 linux-libc-dev mime-support pkg-config python-pip-whl python3
[balena-cam]    python3-dev python3-minimal python3-pip python3-pkg-resources
[balena-cam]    python3-setuptools python3.5 python3.5-dev python3.5-minimal qtcore4-l10n
[balena-cam]    shared-mime-info ucf v4l-utils x11-common x11proto-composite-dev
[balena-cam]    x11proto-core-dev x11proto-damage-dev x11proto-fixes-dev x11proto-input-dev
[balena-cam]    x11proto-kb-dev x11proto-randr-dev x11proto-render-dev x11proto-xext-dev
[balena-cam]    x11proto-xinerama-dev xkb-data xorg-sgml-doctools xtrans-dev zlib1g-dev
[balena-cam]  0 upgraded, 353 newly installed, 0 to remove and 6 not upgraded.
[balena-cam]  Need to get 200 MB of archives.
[balena-cam]  After this operation, 594 MB of additional disk space will be used.
[balena-cam]  WARNING: The following packages cannot be authenticated!
[balena-cam]    libjasper1 libmng1 libjasper-dev
[balena-cam]  E: There were unauthenticated packages and -y was used without --allow-unauthenticated
[balena-cam]  
[balena-cam]  Removing intermediate container f2757c715856
[Info]        Uploading images
[balena-cam]  The command '/bin/sh -c apt-get update &&   apt-get install -yq     gstreamer-1.0     v4l-utils     libopus-dev     libvpx-dev     python3     python3-dev     python3-pip     python3-setuptools     libsrtp2-dev     libopencv-dev     libatlas3-base     libjasper-dev     libilmbase12     libopenexr22     libavformat-dev     libswscale-dev     libqtgui4     libqt4-test     libavdevice-dev     libavfilter-dev     libavcodec-dev   && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
[Success]     Successfully uploaded images
[Error]       Some services failed to build:
[Error]         Service: balena-cam
[Error]           Error: The command '/bin/sh -c apt-get update &&   apt-get install -yq     gstreamer-1.0     v4l-utils     libopus-dev     libvpx-dev     python3     python3-dev     python3-pip     python3-setuptools     libsrtp2-dev     libopencv-dev     libatlas3-base     libjasper-dev     libilmbase12     libopenexr22     libavformat-dev     libswscale-dev     libqtgui4     libqt4-test     libavdevice-dev     libavfilter-dev     libavcodec-dev   && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
[Error]       Not deploying release.
Remote build failed

Additional information may be available in debug mode. Prefix the command
line with DEBUG=1, i.e.:  DEBUG=1 balena ...
If you need help, don't hesitate in contacting us at:

  Forums: https://forums.balena.io
  GitHub: https://github.com/balena-io/balena-cli/issues/new

```

</p>
</details>

This error can be easily be fixed by adding `--allow-unauthenticated` to the `apt-get install -yq` in the `Dockerfile.template` at line 6.

After that I encounter another issue that I am unable to solve, checkout the log (unrelevant bits have been removed.

```
[balena-cam]  ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
[balena-cam]      opencv-python==3.4.4.19 from https://www.piwheels.org/simple/opencv-python/opencv_python-3.4.4.19-cp35-cp35m-linux_armv6l.whl#sha256=329d9d9fdd62b93d44a485aeaab4602c6f5b8555ea8bcc7dbcdc62c90cfe2c3f:
[balena-cam]          Expected sha256 329d9d9fdd62b93d44a485aeaab4602c6f5b8555ea8bcc7dbcdc62c90cfe2c3f
[balena-cam]               Got        3a32f926e1b319f5813ef8574b7dd3ac427768786ef0efc4a5256eb1a9b8bbe5
[balena-cam]  
[balena-cam]  Removing intermediate container f74fea06ff9b
[Info]        Uploading images
[balena-cam]  The command '/bin/sh -c pip3 install aiohttp aiohttp_basicauth==0.1.3 aiortc==0.9.11 opencv-python==3.4.4.19 --index-url https://www.piwheels.org/simple' returned a non-zero code: 1
```

**Comment by mbalamat** [comment]
@idoodler I looked into it, this is an issue with piwheels, I am working on a fix. Thanks for the feedback.

**Comment by mbalamat** [comment]
@idoodler Looking into it

**Comment by mbalamat** [comment]
@idoodler can you try this branch https://github.com/balena-io-playground/balena-cam/tree/fix_hash_mismatch

**Comment by idoodler** [comment]
@mbalamat I can push the project, but the service keeps restarting on my Raspberry Pi Zero W

**Comment by mbalamat** [comment]
@idoodler I located the error to `opencv-python` throwing `illegal instruction error` I've raised an issue on piwheels.

**Comment by idoodler** [comment]
@mbalamat Nice, I am curious to know how you debugged it in Balena-Cloud.

**Comment by idoodler** [comment]
Just for context, here is the linked issue: https://github.com/piwheels/packages/issues/43

**Comment by mbalamat** [comment]
@idoodler so on balenaCloud what I did was to set the entrypoint to sleep and then attached to the balenaCam container and did the things I mention on the issue above.

**Comment by mbalamat** [comment]
@idoodler can you try the branch on this PR https://github.com/balena-io-playground/balena-cam/pull/46

**Comment by idoodler** [comment]
@mbalamat I now can push to Balena, but the project fails to run.

```
10.11.19 16:38:24 (+0100)  balena-cam  ImportError: numpy.core.multiarray failed to import
10.11.19 16:38:24 (+0100)  balena-cam  Traceback (most recent call last):
10.11.19 16:38:24 (+0100)  balena-cam    File "/usr/src/app/server.py", line 1, in <module>
10.11.19 16:38:24 (+0100)  balena-cam      import asyncio, json, os, cv2, platform, sys
10.11.19 16:38:24 (+0100)  balena-cam    File "/usr/local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
10.11.19 16:38:24 (+0100)  balena-cam      from .cv2 import *
10.11.19 16:38:24 (+0100)  balena-cam  ImportError: numpy.core.multiarray failed to import
10.11.19 16:38:44 (+0100)  balena-cam  ImportError: numpy.core.multiarray failed to import
10.11.19 16:38:44 (+0100)  balena-cam  Traceback (most recent call last):
10.11.19 16:38:44 (+0100)  balena-cam    File "/usr/src/app/server.py", line 1, in <module>
10.11.19 16:38:44 (+0100)  balena-cam      import asyncio, json, os, cv2, platform, sys
10.11.19 16:38:44 (+0100)  balena-cam    File "/usr/local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
10.11.19 16:38:44 (+0100)  balena-cam      from .cv2 import *
10.11.19 16:38:44 (+0100)  balena-cam  ImportError: numpy.core.multiarray failed to import
10.11.19 16:38:48 (+0100) Service exited 'balena-cam sha256:d0fc838918c4660a70127437850c7b8486405fe503fd8cada8029960c6cdb125'
10.11.19 16:38:53 (+0100) Restarting service 'balena-cam sha256:d0fc838918c4660a70127437850c7b8486405fe503fd8cada8029960c6cdb125'
```

**Comment by idoodler** [comment]
@mbalamat If you don't have access to a Raspberry Pi Zero W you can send me the image, I will burn it to  an SD card, so you can debug it on a real device.

**Comment by mbalamat** [comment]
@idoodler unboxing one now and setting it up to debug this...

**Comment by mbalamat** [comment]
@idoodler my pi zero is probably fried can you add me as a developer at your balena cloud app that has a pi zero device with camera? You do this from the dashboard >> Members tab on the left

**Comment by idoodler** [comment]
@mbalamat Sure, I just added you. My internet is currently terrible due to some provider issues, so fetching the project may be slow.

**Comment by mbalamat** [comment]
@idoodler thanks I made some progress I'll check it later in the day. Everything build and imports correctly now. But there is an issue which camera device to use.

**Comment by mbalamat** [comment]
@idoodler can you use this branch https://github.com/balena-io-playground/balena-cam/tree/pinned-base-image and try to change the capture device here https://github.com/balena-io-playground/balena-cam/blob/ddf6acd6ef3c88dd9e4886a612dd3de6318c4507/balena-cam/app/server.py#L10 also try to unplug/plug the camera on the device because I see 3 `/dev/video*`. For docs reference https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html

**Comment by idoodler** [comment]
@mbalamat Thx for your help. After reconnecting the Camera I successfully can fetch the MJPEG stream, however WebRTC is not working. Thats not a big deal, because I only need MJPEG. I guess the CPU is a bit to tiny.

Also, the device appears to be offline in balena cloud when starting a stream. So the fix was to update to the latest balena image + applying the fixes you made to this project?

**Comment by idoodler** [comment]
@mbalamat Update, I just remembered about a WebRTC project I worked on back then. Firefox is working correctly, Chrome and Safari won't due to missing HTTPS connection to the Raspberry.

Do you still need to be a member of my project?

**Comment by mbalamat** [comment]
@idoodler which project are you referring to? So just to clarify you just unplugged/plugged the camera and the everything works on the pi zero only when you use firefox?

**Comment by idoodler** [comment]
@mbalamat Yes, I removed the Cameras Flex cable from the Raspberry Pi Zero W and plugged it back in again. That fixed the error with the missing Camera Device. I then wanted to view the camera stream via the local IP. Both Chrome and Safari Desktop won't show an image. Safari Mobile on iOS 13 (Only tried it externaly tho) and Firefox Desktop shows a camera stream.

The issue refered here is solved. Uploading to BalenaCloud works again. I will investigate in the Browser difference when I am at home again.

**Comment by mbalamat** [comment]
@idoodler thanks for your help!

**Comment by mbalamat** [comment]
@idoodler btw you can use the public url in order to use the app from the internet. And it also has https through balena's proxy. https://www.balena.io/docs/learn/manage/actions/#enable-public-device-url
